### ISSUE TITLE
Implement features for a better game development PM workflow

### ISSUE THREAD

**Issue by and-rad** [and-rad/gitea#1]
### Feature Description

Gitea is missing some features that would make it faster to manage video game projects. Faster here largely means "fewer clicks to get somewhere or do something". There are also pieces of information missing on some views that would provide a better overview over an issue's status.

### What's so Special About Video Games?

In the development of a video game there is typically a document that's called the *design document* or *design model*. It grows as development goes on and gets to be fairly sizeable by the time the project nears completion. It is extremely helpful to be able to link issues and tasks with design model elements in order to keep an eye on what needs to be done to complete a feature. It is also very convenient to arrange design model elements flexibly instead of as a bunch of static wiki pages.

Take a look at [HacknPlan](https://hacknplan.com/) for a feature-rich project management system specifically tailored to video game development.

### Subtasks

- [x] Make issue dependencies part of the progress counter and add them to the issue list
- [x] Create a Backlog shortcut to quickly list all issues that can be considered to be in the backlog
- [x] Add top bar to project view that links to all the other projects in the repo
- [x] Show progress bar on an issue's card in the project view
- [x] Remove unimportant information (creation date and author) from issue cards in the project view
- [ ] Autocomplete for issue links in text editor
- [ ] Find a way to apply these changes to some repos only instead of the entire Gitea instance
- [x] Automatic project assignment via issue templates
- [x] Automatic milestone assignment via issue templates
- [x] Deeper integration for proper effort estimation
- [ ] (Optional) Assign custom icons to project boards
- [x] Create label set
- [x] Improve inline issue display

**Comment by and-rad** [comment]
After some deliberation, it's been decided that effort estimation doesn't have to be more sophisticated than what scoped labels can provide. Percentage done seems to be an antipattern when it comes to agile methodologies. Velocity tracking seems useful, but I'm wondering whether this can be achieved with actions.
